### PR TITLE
build: Upgrade of core dependencies

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Upgrade of core dependencies
 - google.oauth-client 1.27.0- -> 1.31.5
- fabric8.kubernetes-client 5.6 -> 5.7
- postgresql jdbc driver 42.2.2 -> 42.2.23
- slf4j 1.7.24 -> 1.7.32
NO CQ required for this change.

### Screenshot/screencast of this PR
Tested on minikube
Знімок екрана 2021-08-16 о 13 27 33

Знімок екрана 2021-08-16 о 10 27 13
openshift 4.8
Знімок екрана 2021-08-16 о 10 27 04
Знімок екрана 2021-08-16 о 13 27 38

### What issues does this PR fix or reference?
 - https://github.com/redhat-developer/codeready-workspaces-images/issues/84
 - https://github.com/redhat-developer/codeready-workspaces-images/issues/82
 - https://github.com/redhat-developer/codeready-workspaces-images/issues/83

### How to test this PR?
 - deploy che -server image
 - start workspace

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
[crw-ci-test --rebuild]

**Comment by skabashnyuk** [comment]
[crw-ci-test --rebuild]

**Review by sparkoo — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Comment by skabashnyuk** [comment]
[crw-ci-test --rebuild]

**Pull request merged**
