### PR TITLE
chore: Update dependencies list

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
- Sort list of dependencies  https://github.com/che-incubator/dash-licenses/pull/10
- Update with latest CQ

### Screenshot/screencast of this PR
n/a

### What issues does this PR fix or reference?
n/a

### How to test this PR?
- build https://github.com/che-incubator/dash-licenses/pull/10 with https://github.com/che-incubator/dash-licenses/blob/main/build.sh
 - mvn clean install
 - cd assembly/assembly-wsmaster-war
 - then
 ```
 docker run --rm -t \
       -v ~/.m2:/root/.m2 \
       -v ${PWD}/:/workspace/project  \
       quay.io/che-incubator/dash-licenses:local --generate --debug
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sparkoo** [comment]
can we add script to generate this into the repository? Or at least include it in some readme.

**Comment by skabashnyuk** [comment]
>can we add script to generate this into the repository? Or at least include it in some readme.

I would like to make as a separate pr:
 -  a github action that is constantly checking if the list is up to date
 -  a script in assembly/assembly-wsmaster-war to generate it.

@sparkoo would it be ok for you?

**Comment by sparkoo** [comment]
is it up to date with latest master changesets?

**Comment by skabashnyuk** [comment]
>is it up to date with latest master changesets?

@sparkoo yes

**Review by sparkoo — APPROVED** [review]

**Pull request merged**
