### PR TITLE
Use `login` instead of `name` in the GitHub scopes/username request

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Change `user.getName()` to `user.getLogin()` in the GitHub `getTokenScopes()` API request, in order to fix a bug where `NullPointer` exception is appeared when a GitHub user request returns a user with `null` in the `name` field.

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/22413

### How to test this PR?

1. In your GitHub profile clear the `Name` input and hit `Save`
2. In your user namespace remove next secrets:
- `personal-access-token-****`
- `git-credentials-secret-****`
- `devworkspace-merged-git-credentials`
3. Apply [GitHub OAuth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/)
4. Start a workspace from GitHub repo

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Comment by ibuziuk** [comment]
Please, backport to 7.72.x for 3.8 once merged

**Review by ScrewTSW — APPROVED** [review]
Verified with `quay.io/eclipse/che-server:pr-537`

Added personal access token (classic)
Verified workspace creation from private repository using both ssh and https.

**Comment by vinokurig** [comment]
@ibuziuk 
> Please, backport to 7.72.x for 3.8 once merged

done

**Pull request merged**
