### PR TITLE
Do not throw an error on token refresh when starting a workspace

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Intercept exceptions in the `token/refresh` method of the `FactoryService` in order to not to interrupt the workspace start flow if something wrong happens on the token refresh step. For example the workspace project is public and no corresponding oauth is configured.

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-5015

### How to test this PR?

1. Deploy che from the PR image: `quay.io/eclipse/che-server:pr-609`
2. Create a workspace from a public gitlab-server repository.
3. Stop the workspace and start it again.

See: workspace starts without any issues.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
What happens if project is private and token is requried?

**Comment by vinokurig** [comment]
@tolusha 
> What happens if project is private and token is required?

If the corresponding oauth config is present, `ScmUnauthorizedException` will be thrown:
https://github.com/eclipse-che/che-server/blob/379ce02be2d3f345e12e8ed55c05c9e2e880d688/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java#L167-L171
and the dashboard will redirect to the authentication page. Otherwise the workspacce will start without the token.
> How did it work before?

The `UnknownScmProviderException` was ignored before this dashboard PR: https://github.com/eclipse-che/che-dashboard/pull/970

**Comment by vinokurig** [comment]
Will rework this in the dashboard side

**Comment by vinokurig** [comment]
Opened the related dashboard PR https://github.com/eclipse-che/che-dashboard/pull/987

**Pull request closed without merging**
