### PR TITLE
Remove devfile validation schema mechanism

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Remove devfile validation schema mechanism and related stuff.

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/22755

### How to test this PR?

1. Deploy CHE from the PR image: `quay.io/eclipse/che-server:pr-640`
2. Start a workspace from a repository with the latest version of devfile, e.g. https://github.com/vinokurig/test.git

See: workspace starts successfully.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Comment by svor** [comment]
@vinokurig there is a typo in the description, the image should be quay.io/eclipse/che-ser**v**er:pr-640

**Review by svor — APPROVED** [review]
LGTM

Valid devfile:
screenshot-eclipse-che apps ci-ln-4cq5nmb-76ef8 aws-2 ci openshift org-2024 01 15-19_37_56

Not valid devfile:
screenshot-eclipse-che apps ci-ln-4cq5nmb-76ef8 aws-2 ci openshift org-2024 01 15-19_32_46

**Review by artaleks9 — APPROVED** [review]

**Pull request merged**
