### PR TITLE
feat: Allow to configure 2 github providers simultaneously

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Allow to configure 2 github providers simultaneously

### Screenshot/screencast of this PR

Screenshot from 2023-10-27 15-29-30

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-4840

### How to test this PR?

1. Deploy Che `chectl server:deploy -p minikube --cheimage=quay.io/eclipse/che-server:pr-598`
2. Configure OAuth for 2 GitHub providers https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/
3. Try to clone projects from different GitHub providers

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dkwon17** [comment]
I am interested in testing this PR with github.com and github enterprise

**Review by vinokurig — APPROVED** [review]
Tested according to the provided description.

**Comment by vinokurig** [comment]
@tolusha Please also update the documentation to clarify how to add two github-oauth secrets with different names.

**Comment by dkwon17** [comment]
I was able to reach the auth page after setting up both instances:
<details><summary>Screenshots</summary>

github.com:

Screenshot_4

github enterprise:
image

Screenshot_6

</details>

but I wasn't able to clone with a GitHub enterprise repository (maybe a problem with my setup?):

Project clone container logs:
```
2023/11/03 22:10:16 Using temporary directory /projects/project-clone-1123615913
2023/11/03 22:10:16 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2023/11/03 22:10:16 Processing project my-amazing-repo
2023/11/03 22:10:16 Cloning project my-amazing-repo to /projects/project-clone-1123615913/my-amazing-repo
Cloning into '/projects/project-clone-1123615913/my-amazing-repo'...
fatal: could not read Username for 'https://10.0.0.70': No such device or address
2023/11/03 22:10:16 Encountered error while setting up project my-amazing-repo: failed to clone project: failed to git clone from https://10.0.0.70/my-user/my-amazing-repo.git: exit status 128
```

**Comment by tolusha** [comment]
@dkwon17 

My environments was the following:
* Minikube is run with `--vm-driver=virtualbox`
* I used `.nio.io` prefix for GitHub Server Enterprise host (see screenshot above)

**Review by ibuziuk — COMMENTED** [review]
@tolusha looks like PR needs to be rebased on main + version in newly added pom should be 7.77 SNAPSHOT

**Review by dkwon17 — APPROVED** [review]
I was able to verify this PR.

Here are the steps I took:
1. Deploy Che `chectl server:deploy -p minikube --cheimage=quay.io/eclipse/che-server:pr-598`
2. Configure OAuth for 2 GitHub providers https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/
3. Follow [Deploying Che with support for Git repositories with self-signed certificates](https://eclipse.dev/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/)
4. Follow [Importing untrusted TLS certificates to Che](https://eclipse.dev/che/docs/stable/administration-guide/importing-untrusted-tls-certificates/) to import the certificate for the github enterprise instance
5. Create workspace with a GitHub project from the github enterprise instance
6. Accept the OAuth prompt and wait until workspace opens and project is cloned
7. Create a workspace with a GitHub project from the github.com instance
8. Accept the OAuth prompt and wait until workspace opens and project is cloned

<details><summary>Repo from github enterprise instance cloned </summary>

image

</details>


<details><summary>Private repo from github.com cloned </summary>

image

</details>

<details><summary>Git services view</summary>

image

</details>

I also tested the flow of revoking the GitHub enterprise instance from the `Git Services` view of the dashboard, and trying to start a github enterprise workspace again. As expected, I get the OAuth prompt again.

**Pull request merged**
