### PR TITLE
Use HTTP response status code to check gitlab repositories accessibility

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Improve the `isPublicRepository()` function in the `GitlabAuthorizingFileContentProvider` class to check the http response status code. The previous way with the `urlFetcher` does not work because gitlab server returns a content of an html page with credentials input instead of an error.

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-7608

### How to test this PR?

1. Deploy che with the pull request image: `quay.io/eclipse/che-server:pr-741`
2. Start a workspace from a private gitlab server repository.

See: workspace start fails with the expected error message:
screenshot-eclipse-che_apps_rosa_p9t96-996tb-ydw_ylq7_p3_openshiftapps_com-2024_11_18-12_43_37

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Release Notes
With this fix workspace start from a private gitlab repository will interrupt with an error if no token is present. 
### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by artaleks9** [comment]
Verified on Eclipse Che with `quay.io/eclipse/che-server:pr-741`

The functionality works properly.

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [sync-to-downstream_3.x/8112](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8112/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8112/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8112/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8112/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/8189](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8189/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8189/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8189/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8189/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [push-latest-container-to-quay_3.x/5025](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/5025/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/5025/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/5025/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/5025/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/8189](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8189/): [SUCCESS](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/8189/)<br /><blockquote>server : 3.x :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=65955846'> Build  65955846</a> : <a href=https://quay.io/devspaces/server-rhel8:3.18-12>quay.io/devspaces/server-rhel8:3.18-12</a> <br /> SUCCESS; copied to quay; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/5025/>/DS_CI/push-latest-container-to-quay_3.x/5025</a> triggered</blockquote>

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [update-digests_3.x/8013](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/8013/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/8013/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/8013/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/8013/git)

**Comment by devspacesbuild** [comment]
Build [3.18](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [server_3.x/373](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/server_3.x/373/): [SUCCESS](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/server_3.x/373/)<br /><blockquote>Upstream sync done; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/8112/>/DS_CI/sync-to-downstream_3.x/8112</a> triggered</blockquote>

**Pull request merged**
