### PR TITLE
Dummy changes

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It checks Happy path PR check on CRW Jenkins Ci

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19836

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sparkoo** [comment]
I like it ❤️ :)

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
@skabashnyuk: looks like this repo doesn't have settings for che-bot webhook to trigger CRW Jenkins CI tests.

Could you, please, ensure che-bot webhook has been set up in the same way, as it was done in eclipse/che repo?

**Comment by skabashnyuk** [comment]
@dmytro-ndp  that is easy you just need to create an issue for Eclipse Webmaster

**Comment by dmytro-ndp** [comment]
@skabashnyuk: webhook should have payload URL = https://smee.io/pRtJXvHGV9e8Zth, and be triggered on push event and comments in PR. 
It would be the best if Eclipse Webmaster has just copied `https://smee.io/pRtJXvHGV9e8Zth,` payload settings from eclipse/che repo.

**Comment by dmytro-ndp** [comment]
@skabashnyuk: FYI: the bug ticket to add webhook for Happy path PR check: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573756

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Pull request closed without merging**
