### PR TITLE
chore: Expose dashboard ingress path

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Expose dashboard ingress path. By default it is set to `/dashboard'.
To override a default value pls use `--helm-patch-yaml` flag with `chectl`:

```bash
cat >patch.yaml<<EOF
> dashboard:
>   ingressPath: /dashboard/*
> EOF
chectl server:deploy --installer=helm < .... >  --helm-patch-yaml patch.yaml
```

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19914

### How to test this PR?

1. `cd deploy/kubernetes/helm/che`
2. `helm dependency update`
3. `chectl server:deploy --installer=helm --platform=minikube  --multiuser  --templates ../../..`
4. `chectl dashboard:open` check if dashboard is opened in a browser

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by skabashnyuk** [comment]
@tolusha do we need to change something in our documentation?

**Comment by tolusha** [comment]
@skabashnyuk 
sure, this doc https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-google-cloud-platform/

**Review by sparkoo — APPROVED** [review]

**Comment by tolusha** [comment]
@skabashnyuk 
https://github.com/eclipse/che-docs/pull/2018

**Pull request merged**
