### PR TITLE
Skip refresh GitHub tokens, override refresh Azure DevOps token request

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
* Return existed token on GitHub token refresh request. GitHub Oauth tokens do not have expiration date, so no need to refresh them. Refresh token request will fail for such tokens because they do not have `expires_in ` value, see: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens#refreshing-a-user-access-token-with-a-refresh-token
* Override the `refreshToken` function for Azure DevOps. The existed refresh function from the `oauth2` package fails because Azure DevOps supports POST requests  in `application/x-www-form-urlencoded` format only.

### What issues does this PR fix or reference?

fixes https://github.com/eclipse-che/che/issues/23028

### How to test this PR?

see https://github.com/eclipse-che/che/issues/23028
Same steps are relevant for Azure DevOps

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by artaleks9** [comment]
Verified on Eclipse Che with `quay.io/eclipse/che-server:pr-699` - **the functionality works properly.**

**Review by artaleks9 — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
