### PR TITLE
Update io.fabric8.kubernetes-client version to latest

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Update `io.fabric8.kubernetes-client` version to 6.8.1

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/22452

### How to test this PR?

 Deploy Che from the PR image: `quay.io/eclipse/che-server:pr-549`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@vinokurig great job :+1:  Could you please provide the image for testing? Also got some feedback from  @manusa that we probaly still need to have `kubernetes-client` (not just `kubernetes-client-api`) which contains implementations required at runtime. However, I'm baffled that our PR checks have not spotted any problems ¯\_(ツ)_/¯

**Review by amisevsk — APPROVED** [review]

**Comment by vinokurig** [comment]
@ibuziuk @manusa
>  we probaly still need to have `kubernetes-client` (not just `kubernetes-client-api`) which contains implementations required at runtime.

Maven build fails with this error if I add the `kubernetes-client` dependency:
```
[WARNING] Unused declared dependencies found:
[WARNING]    io.fabric8:kubernetes-client:jar:6.8.1:compile
```
> Could you please provide the image for testing?

Updated the PR's description with the image.

**Comment by manusa** [comment]
You need to declare the kubernetes-client dependency as `runtime`:
```
<dependencies>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-client</artifactId>
      <scope>runtime</scope>
    </dependency>
</dependencies>
```
If you don't add the client (implementation) dependency, then whatever you do with the client at runtime will fail.

**Comment by vinokurig** [comment]
I've verified the PR image on OpenShift cluster and on minikube. The client didn't fail but worked as expected.
@manusa @ibuziuk Do you think we still need the `kubernetes-client` runtime dependency?

**Comment by manusa** [comment]
I'm not really sure how that is actually working since the client implementations are in the client module. Likely the dependency is coming from elsewhere, otherwise it's pretty weird.

**Comment by vinokurig** [comment]
Looks like the dependency comes from the `infrastructure/openshift` module:
```
[INFO] +- io.fabric8:openshift-client:jar:6.8.1:compile
[INFO] |  +- io.fabric8:kubernetes-client:jar:6.8.1:compile
```

**Comment by manusa** [comment]
OK, so you do have a dependency for openshift-client which bring in the kubernetes-client.
It's fine then.
Both openshift-client and kubernetes-client are runtime dependencies. For compilation purposes you only need the `xxx-client-api` modules. However, at runtime you'll need the effective clients.

**Comment by ibuziuk** [comment]
> OK, so you do have a dependency for openshift-client which bring in the kubernetes-client.
It's fine then.

@vinokurig wondering if the PR has been verified on vanilla k8s?

**Comment by vinokurig** [comment]
@ibuziuk 
> wondering if the PR has been verified on vanilla k8s?

If `minikube` can be considered as vanilla k8s, then yes.

**Review by ibuziuk — APPROVED** [review]
great job :+1:

**Pull request merged**
