### PR TITLE
chore: switch to default editor = che-incubator/che-code/latest

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: switch to default editor = che-incubator/che-code/latest (CRW-3099, CRW-3420, https://github.com/eclipse/che/issues/20500)

Change-Id: Ib576241488e9ada5465dd45a9bc140cd6b4ed7e6
Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-3099, 
https://issues.redhat.com/browse/CRW-3420, 
https://github.com/eclipse/che/issues/20500

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ibuziuk — CHANGES_REQUESTED** [review]
I do not think the PR is relevant
@nickboldt could you clarify how was it tested?

**Comment by nickboldt** [comment]
> how was it tested?

Other than the automated checks, it was not manually tested.

**Comment by themr0c** [comment]
I don't know why @MichalMaler and @themr0c are marked as reviewers: you can safely remove us from the reviewer list.
If you need docs team reviewers, it should rather be: @rkratky, @max-cx, @deerskindoll and @osslate.

**Comment by nickboldt** [comment]
@ibuziuk so should we merge this or wait until 7.62 / 3.6 when we're removing theia entirely...?

**Comment by nickboldt** [comment]
@themr0c: 
> I don't know why @MichalMaler and @themr0c are marked as reviewers: you can safely remove us from the reviewer list.
If you need docs team reviewers, it should rather be: @rkratky, @max-cx, @deerskindoll and @osslate.

See https://github.com/eclipse-che/che-server/pull/434 - in which I'm removing and simplifying the CODEOWNERS to exclude people who shouldn't be there anymore.

**Comment by l0rd** [comment]
I am not sure what's your purpose @nickboldt but the [default editor is specified here](https://github.com/eclipse-che/che-operator/blob/main/api/v2/checluster_types.go#L93). These properties are not used anymore.

**Comment by ibuziuk** [comment]
closing as irrelevant

**Pull request closed without merging**
