### PR TITLE
feat: Add a predefined configmap to store theia preferences

### PR DESCRIPTION
**Pull request by vinokurig**
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### What does this PR do?
* Create a predefined K8s secret per nemaespace to store theia preferences.
* Include the preference secret to the `workspcae-secrets` role, to be able to manage it outside.

See https://github.com/eclipse-che/che-server/pull/172#issuecomment-953729818
### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20622

### How to test this PR?

1. Start a workspace and open a terminal from the ide container.
2. Send an HTTP request to the kubernetes API to edit user-preferences secret: `curl -X POST <kubernetes API url>/api/v1/namespaces/<namespace name>/secrets/workspace-theia-secret --header "Content-Type: application/json-patch+json" -d '[{ "op": "add", "path": "/data", "value": { "key": "" } }]'`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Are we going to have a separate secret for each ide? Should we make the name of it ide-neutral? For example `editor-preferences`?

**Comment by svor** [comment]
@vinokurig would it be a problem to save preferences of all editors in one secret?

**Comment by benoitf** [comment]
> Are we going to have a separate secret for each ide? Should we make the name of it ide-neutral? For example editor-preferences?

I think it's what @l0rd wanted

**Comment by skabashnyuk** [comment]
>>Are we going to have a separate secret for each ide? Should we make the name of it ide-neutral? For example editor-preferences?

>I think it's what @l0rd wanted (preferences per ide)

Can we do that in a way that we don't need to adjust che-server's source code for each?

**Comment by benoitf** [comment]
I would say for sure it makes sense that as there are multiple editors and we don't know all editors in advance, it should be generic enough

**Comment by vinokurig** [comment]
@svor @skabashnyuk @benoitf @l0rd Renamed the secret to `workspace-preferences-secret` so that we can use it as a single secret for all editors

**Review by skabashnyuk — APPROVED** [review]

**Comment by l0rd** [comment]
I am ok with this approach

**Comment by vinokurig** [comment]
I am going to merge it after the `che-theia` part is finished.

**Comment by vinokurig** [comment]
@skabashnyuk @l0rd From the discussion [here](https://github.com/eclipse/che/issues/20749#issuecomment-970512272) it was decided to use `config-map` for storing preferences. My last commit reworks the PR to use `config-map` instead of secret, could you please take a look?

**Comment by vinokurig** [comment]
depends on https://github.com/eclipse-che/che-operator/pull/1180

**Review by amisevsk — APPROVED** [review]

**Comment by svor** [comment]
@skabashnyuk ok to merge?

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
