### PR TITLE
feat: Allow to configure 2 gitlab providers simultaneously

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Allow to configure 2 gitlab providers simultaneously

### Screenshot/screencast of this PR

screenshot-cluster-admin-che-dashboard-local-server_apps_rosa_oaky8-tf8zx-r5p_asdn_p3_openshiftapps_com-2024_10_23-11_53_49
screenshot-cluster-admin-che-dashboard-local-server_apps_rosa_oaky8-tf8zx-r5p_asdn_p3_openshiftapps_com-2024_10_23-11_54_23

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-7142

### How to test this PR?

1. Deploy `che-server` image: `quay.io/eclipse/che-server:pr-731` 
2. Deploy `che-operator` image: `quay.io/ivinokur/che-operator:next`
3. Deploy `che-dashboard` image: `quay.io/eclipse/che-dashboard:pr-1237`
4. [Configure oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/) for two gitlab instances, add a random suffix for the second oauth secret name.
5. Start a workspace from each gitlab repository with a devfille.
6. See: personal access token is generated for both gitlab instances.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Release Notes
With this feature it is possible to configure two Gitlab oauth providers simultaneously.
### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by tolusha** [comment]
Only the first GitLab provider can be revoked. 

screenshot-eclipse-che_apps_ci-ln-27mym1b-76ef8_aws-2_ci_openshift_org-2024_10_25-12_37_37

**Comment by vinokurig** [comment]
@tolusha 
> Only the first GitLab provider can be revoked.

Should be fixed by the dashboard pull request fixup.

**Comment by artaleks9** [comment]
Verified on Eclipse Che with gitlab server and GitLab.com using
```
quay.io/eclipse/che-server:pr-731
quay.io/ivinokur/che-operator:next
quay.io/eclipse/che-dashboard:pr-1237
```
**The functionality works properly.**

 ------------------

 Verification with two gitlab servers is still in progress.

**Comment by artaleks9** [comment]
Verification with two gitlab servers is finished.
**The functionality also woks properly.**

See screenshots:
pr73-git-sevices
pr731-pat-dashboard

**Review by artaleks9 — APPROVED** [review]

**Review by tolusha — APPROVED** [review]

**Pull request merged**
