### PR TITLE
fix: Omit default branch for GitLab repositories as it is not always 'master'

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Fixes the GitLab file reading behavior, by omitting `master` branch name by default.

### How to test this PR?
Before PR: Accepting factory with GitLab repository, having default branch other than 'master' is failing;
After PR: Accepting factory with GitLab repository, having default branch other than 'master' is OK;

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by l0rd** [comment]
@mshaposhnik is there any issue associated to this PR? I am asking because we would like to add it to the release notes of 7.32 (and CRW 2.10).

**Comment by mshaposhnik** [comment]
@lord it cane from CRW testing, so i hve only this: https://issues.redhat.com/browse/CRW-1929

**Comment by l0rd** [comment]
@mshaposhnik cool thanks

**Comment by MichalMaler** [comment]
https://issues.redhat.com/browse/CRW-1962

**Pull request merged**
